import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'hi' | 'mr';

interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी (Marathi)', flag: '🇮🇳' },
  { code: 'es', name: 'Español (Spanish)', flag: '🇪🇸' },
  { code: 'fr', name: 'Français (French)', flag: '🇫🇷' },
];

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    appName: "JanSeva",
    tagline: "Apki awaaz, Apka samadhan",
    map: "Map",
    impact: "Impact",
    report: "Report Issue",
    leaderboard: "Leaderboard",
    signOut: "Sign Out",
    heroPoints: "Hero Points",
    filter: "Filter",
    allIssues: "All Issues",
    pothole: "Potholes",
    waterLeak: "Water Leakages",
    brokenLight: "Broken Streetlights",
    garbage: "Waste / Garbage",
    critical: "Critical",
    resolved: "Resolved",
    totalReported: "Total Reported",
    open: "Open",
    streetView: "Street View",
    details: "Details",
    location: "Location",
    reportHeader: "Report a Local Civic Issue",
    reportSub: "Take a photo of the issue. Our AI will automatically classify category, severity, and suggest the responsible department.",
    photoRequired: "Issue Photo (Required)",
    uploadText: "Upload or Take Photo",
    uploadSub: "Accepts any camera image",
    aiAnalyzing: "AI is analyzing your image...",
    aiAnalyzingSub: "Detecting issue, severity & department",
    aiComplete: "AI Auto-Classification Complete!",
    aiSuggesting: "AI is analyzing description to suggest category & severity...",
    aiSuggestBtn: "Auto-Suggest with AI",
    confidence: "Confidence Score",
    issueTitle: "Issue Title",
    category: "Category",
    severity: "Severity Level",
    description: "Detailed Description",
    descriptionPlaceholder: "Provide context like nearby landmarks or hazards...",
    suggestedDept: "Suggested Department",
    pinpointLocation: "Pinpoint Issue Location",
    mapClickTip: "Click anywhere on the map or drag the marker to precisely indicate where the issue is.",
    resetGps: "Reset to GPS",
    latitude: "Latitude",
    longitude: "Longitude",
    gpsLive: "GPS Live",
    gpsLoading: "Loading GPS...",
    gpsUnavailable: "GPS unavailable",
    submitReport: "Submit Civic Report",
    submitting: "Submitting report...",
    inspections: "Virtual Site Inspection",
    inspectionTip: "Inspect the surrounding environment to verify details, search for landmarks, or validate reported civic blockages directly from your screen.",
    geoLoc: "Geographical Location",
    timeline: "Progress Timeline",
    upvotes: "Upvotes",
    others: "Others",
    viewProfile: "View Profile",
    pointsEarned: "Total Points",
    submissions: "My Submissions",
    personalSettings: "Personal Settings",
    badgesTab: "Badges & Achievements",
    updateSuccess: "Profile updated successfully!",
    saveChanges: "Save Changes",
    bioLabel: "Bio / Contribution Statement",
    phoneLabel: "Phone Number",
    notificationsEnabledLabel: "Enable Email Alerts",
    chooseAvatar: "Choose Avatar Emoji",
    yourRank: "Leaderboard Rank",
    videoOptional: "Video Evidence (Optional)",
    videoUploadSub: "Short video under 750KB to show dynamic context.",
    videoUploading: "Reading video...",
    removeVideo: "Remove Video",
    incidentDate: "Incident / Observation Date",
    incidentDateSub: "Specify the date when this civic issue was first seen or occurred",
  },
  hi: {
    appName: "जनसेवा",
    tagline: "आपकी आवाज, आपका समाधान",
    map: "नक्शा",
    impact: "प्रभाव",
    report: "समस्या रिपोर्ट करें",
    leaderboard: "लीडरबोर्ड",
    signOut: "साइन आउट",
    heroPoints: "हीरो पॉइंट्स",
    filter: "फ़िल्टर",
    allIssues: "सभी मुद्दे",
    pothole: "गड्ढे",
    waterLeak: "पानी का रिसाव",
    brokenLight: "टूटी स्ट्रीटलाइट",
    garbage: "कचरा / वेस्ट",
    critical: "गंभीर",
    resolved: "समाधानित",
    totalReported: "कुल रिपोर्ट",
    open: "खुली समस्याएं",
    streetView: "स्ट्रीट व्यू",
    details: "विवरण",
    location: "स्थान",
    reportHeader: "स्थानीय नागरिक समस्या की रिपोर्ट करें",
    reportSub: "समस्या की एक तस्वीर लें। हमारा एआई स्वचालित रूप से श्रेणी, गंभीरता को वर्गीकृत करेगा और जिम्मेदार विभाग का सुझाव देगा।",
    photoRequired: "समस्या की तस्वीर (अनिवार्य)",
    uploadText: "तस्वीर अपलोड करें या खींचें",
    uploadSub: "कोई भी कैमरा छवि स्वीकार्य है",
    aiAnalyzing: "एआई आपकी छवि का विश्लेषण कर रहा है...",
    aiAnalyzingSub: "समस्या, गंभीरता और विभाग का पता लगाया जा रहा है",
    aiComplete: "एआई स्वचालित वर्गीकरण पूर्ण!",
    aiSuggesting: "एआई श्रेणी और गंभीरता का सुझाव देने के लिए विवरण का विश्लेषण कर रहा है...",
    aiSuggestBtn: "एआई के साथ सुझाव दें",
    confidence: "विश्वास स्कोर",
    issueTitle: "समस्या का शीर्षक",
    category: "श्रेणी",
    severity: "गंभीरता स्तर",
    description: "विस्तृत विवरण",
    descriptionPlaceholder: "आस-पास के स्थलचिह्न या खतरों जैसे संदर्भ प्रदान करें...",
    suggestedDept: "सुझाया गया विभाग",
    pinpointLocation: "समस्या का सटीक स्थान इंगित करें",
    mapClickTip: "नक्शे पर कहीं भी क्लिक करें या मार्कर को खींचकर समस्या का सटीक स्थान निर्दिष्ट करें।",
    resetGps: "जीपीएस पर रीसेट करें",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    gpsLive: "जीपीएस सक्रिय है",
    gpsLoading: "जीपीएस लोड हो रहा है...",
    gpsUnavailable: "जीपीएस अनुपलब्ध",
    submitReport: "नागरिक रिपोर्ट जमा करें",
    submitting: "रिपोर्ट जमा की जा रही है...",
    inspections: "वर्चुअल साइट निरीक्षण",
    inspectionTip: "अपनी स्क्रीन से सीधे नागरिक अवरोधों को सत्यापित करने, स्थलों की खोज करने या रिपोर्ट किए गए विवरणों की जांच करने के लिए आसपास के वातावरण का निरीक्षण करें।",
    geoLoc: "भौगोलिक स्थिति",
    timeline: "प्रगति समयरेखा",
    upvotes: "अपवोट",
    others: "अन्य",
    viewProfile: "प्रोफ़ाइल देखें",
    pointsEarned: "कुल अंक",
    submissions: "मेरी प्रस्तुतियाँ",
    personalSettings: "व्यक्तिगत सेटिंग्स",
    badgesTab: "बैज और उपलब्धियां",
    updateSuccess: "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
    saveChanges: "बदलाव सहेजें",
    bioLabel: "बायो / योगदान विवरण",
    phoneLabel: "फ़ोन नंबर",
    notificationsEnabledLabel: "ईमेल अलर्ट सक्षम करें",
    chooseAvatar: "अवतार इमोजी चुनें",
    yourRank: "लीडरबोर्ड रैंक",
    videoOptional: "वीडियो साक्ष्य (वैकल्पिक)",
    videoUploadSub: "गतिशील संदर्भ दिखाने के लिए 750KB से कम का छोटा वीडियो।",
    videoUploading: "वीडियो पढ़ रहा है...",
    removeVideo: "वीडियो हटाएं",
    incidentDate: "घटना / अवलोकन तिथि",
    incidentDateSub: "वह तारीख बताएं जब यह समस्या पहली बार देखी गई थी",
  },
  mr: {
    appName: "जनसेवा",
    tagline: "तुमचा आवाज, तुमचे समाधान",
    map: "नकाशा",
    impact: "प्रभाव",
    report: "तक्रार नोंदवा",
    leaderboard: "लीडरबोर्ड",
    signOut: "बाहेर पडा",
    heroPoints: "हिरो पॉईंट्स",
    filter: "फिल्टर",
    allIssues: "सर्व समस्या",
    pothole: "खड्डे",
    waterLeak: "पाणी गळती",
    brokenLight: "बंद पथदिवे",
    garbage: "कचरा / कचरा कुंडी",
    critical: "गंभीर",
    resolved: "निवारण झालेले",
    totalReported: "एकूण तक्रारी",
    open: "प्रलंबित समस्या",
    streetView: "स्ट्रीट व्ह्यू",
    details: "तपशील",
    location: "स्थान",
    reportHeader: "स्थानिक नागरी समस्येची तक्रार करा",
    reportSub: "समस्येचा फोटो घ्या. आमचे एआय स्वयंचलितपणे वर्गवारी, गांभीर्य आणि जबाबदार विभाग सुचवेल.",
    photoRequired: "समस्येचा फोटो (आवश्यक)",
    uploadText: "फोटो अपलोड करा किंवा घ्या",
    uploadSub: "कोणताही कॅमेरा फोटो स्वीकारला जाईल",
    aiAnalyzing: "एआय आपल्या फोटोचे विश्लेषण करत आहे...",
    aiAnalyzingSub: "समस्या, गांभीर्य आणि विभाग शोधत आहे",
    aiComplete: "एआय स्वयंचलित वर्गीकरण पूर्ण!",
    aiSuggesting: "एआय श्रेणी आणि गांभीर्य सुचवण्यासाठी वर्णनाचे विश्लेषण करत आहे...",
    aiSuggestBtn: "एआय सह सुचवा",
    confidence: "विश्वासार्हता धावसंख्या",
    issueTitle: "समस्येचे शीर्षक",
    category: "वर्गवारी",
    severity: "गांभीर्याची पातळी",
    description: "सविस्तर वर्णन",
    descriptionPlaceholder: "जवळील महत्त्वाच्या जागा किंवा धोक्यांविषयी माहिती द्या...",
    suggestedDept: "सुचवलेला विभाग",
    pinpointLocation: "समस्येचे अचूक स्थान निवडा",
    mapClickTip: "नकाशावर कुठेही क्लिक करा किंवा मार्कर ओढून समस्येचे अचूक स्थान दर्शवा.",
    resetGps: "जीपीएसवर रीसेट करा",
    latitude: "अक्षांश",
    longitude: "रेखांश",
    gpsLive: "जीपीएस चालू आहे",
    gpsLoading: "जीपीएस लोड होत आहे...",
    gpsUnavailable: "जीपीएस उपलब्ध नाही",
    submitReport: "नागरी तक्रार दाखल करा",
    submitting: "तक्रार दाखल केली जात आहे...",
    inspections: "व्हर्च्युअल साइट तपासणी",
    inspectionTip: "तुमच्या स्क्रीनवरून थेट नागरी अडथळ्यांची पडताळणी करण्यासाठी, खुणा शोधण्यासाठी किंवा तक्रारींच्या तपशीलांची तपासणी करण्यासाठी सभोवतालच्या परिसराचे निरीक्षण करा.",
    geoLoc: "भौगोलिक स्थान",
    timeline: "प्रगती टाइमलाईन",
    upvotes: "मते",
    others: "इतर",
    viewProfile: "प्रोफाईल पहा",
    pointsEarned: "एकूण गुण",
    submissions: "माझ्या सबमिशन",
    personalSettings: "वैयक्तिक सेटिंग्ज",
    badgesTab: "बिल्ले आणि यश",
    updateSuccess: "प्रोफाईल यशस्वीरित्या अपडेट केली!",
    saveChanges: "बदल जतन करा",
    bioLabel: "बायो / योगदान विधान",
    phoneLabel: "फोन नंबर",
    notificationsEnabledLabel: "ईमेल अलर्ट सक्षम करा",
    chooseAvatar: "अवतार इमोजी निवडा",
    yourRank: "लीडरबोर्ड रँक",
    videoOptional: "व्हिडिओ पुरावा (पर्यायी)",
    videoUploadSub: "गतिमान संदर्भ दर्शवण्यासाठी 750KB पेक्षा लहान व्हिडिओ क्लिप.",
    videoUploading: "व्हिडिओ लोड होत आहे...",
    removeVideo: "व्हिडिओ काढा",
    incidentDate: "घटना / निरीक्षण तारीख",
    incidentDateSub: "ती तारीख सांगा जेव्हा ही समस्या पहिल्यांदा दिसून आली",
  },
  es: {
    appName: "JanSeva",
    tagline: "Apki awaaz, Apka samadhan",
    map: "Mapa",
    impact: "Impacto",
    report: "Reportar Problema",
    leaderboard: "Clasificación",
    signOut: "Cerrar Sesión",
    heroPoints: "Puntos de Héroe",
    filter: "Filtrar",
    allIssues: "Todos los Problemas",
    pothole: "Baches",
    waterLeak: "Fugas de Agua",
    brokenLight: "Farolas Rotas",
    garbage: "Residuos / Basura",
    critical: "Crítico",
    resolved: "Resuelto",
    totalReported: "Total Reportado",
    open: "Abierto",
    streetView: "Street View",
    details: "Detalles",
    location: "Ubicación",
    reportHeader: "Reportar un Problema Cívico Local",
    reportSub: "Tome una foto del problema. Nuestra IA clasificará automáticamente la categoría, la gravedad y sugerirá el departamento responsable.",
    photoRequired: "Foto del Problema (Obligatorio)",
    uploadText: "Subir o Tomar Foto",
    uploadSub: "Se acepta cualquier imagen de cámara",
    aiAnalyzing: "La IA está analizando su imagen...",
    aiAnalyzingSub: "Detectando problema, gravedad y departamento",
    aiComplete: "¡Clasificación Automática de IA Completa!",
    aiSuggesting: "La IA está analizando la descripción para sugerir categoría y gravedad...",
    aiSuggestBtn: "Sugerir con IA",
    confidence: "Puntuación de Confianza",
    issueTitle: "Título del Problema",
    category: "Categoría",
    severity: "Nivel de Gravedad",
    description: "Descripción Detallada",
    descriptionPlaceholder: "Proporcione contexto como puntos de referencia cercanos o peligros...",
    suggestedDept: "Departamento Sugerido",
    pinpointLocation: "Señalar Ubicación del Problema",
    mapClickTip: "Haga clic en cualquier lugar del mapa o arrastre el marcador para indicar con precisión dónde está el problema.",
    resetGps: "Restablecer a GPS",
    latitude: "Latitud",
    longitude: "Longitud",
    gpsLive: "GPS Activo",
    gpsLoading: "Cargando GPS...",
    gpsUnavailable: "GPS no disponible",
    submitReport: "Enviar Reporte Cívico",
    submitting: "Enviando reporte...",
    inspections: "Inspección Virtual del Sitio",
    inspectionTip: "Inspeccione el entorno circundante para verificar detalles, buscar puntos de referencia o validar bloqueos cívicos reportados directamente desde su pantalla.",
    geoLoc: "Ubicación Geográfica",
    timeline: "Cronología del Progreso",
    upvotes: "Votos",
    others: "Otros",
    viewProfile: "Ver Perfil",
    pointsEarned: "Puntos Totales",
    submissions: "Mis Envíos",
    personalSettings: "Ajustes Personales",
    badgesTab: "Insignias y Logros",
    updateSuccess: "¡Perfil actualizado con éxito!",
    saveChanges: "Guardar Cambios",
    bioLabel: "Biografía / Declaración de Contribución",
    phoneLabel: "Número de Teléfono",
    notificationsEnabledLabel: "Habilitar Alertas de Correo",
    chooseAvatar: "Elegir Emoji de Avatar",
    yourRank: "Rango de Clasificación",
    videoOptional: "Evidencia de Video (Opcional)",
    videoUploadSub: "Video corto de menos de 750KB para mostrar contexto dinámico.",
    videoUploading: "Procesando video...",
    removeVideo: "Quitar Video",
    incidentDate: "Fecha del incidente",
    incidentDateSub: "Especifique la fecha en que se observó o ocurrió por primera vez",
  },
  fr: {
    appName: "JanSeva",
    tagline: "Apki awaaz, Apka samadhan",
    map: "Carte",
    impact: "Impact",
    report: "Signaler un Problème",
    leaderboard: "Classement",
    signOut: "Se Déconnecter",
    heroPoints: "Points Héros",
    filter: "Filtrer",
    allIssues: "Tous les Problèmes",
    pothole: "Nids-de-poule",
    waterLeak: "Fuites d'Eau",
    brokenLight: "Réverbères Cassés",
    garbage: "Déchets / Ordures",
    critical: "Critique",
    resolved: "Résolu",
    totalReported: "Total Signalé",
    open: "Ouvert",
    streetView: "Street View",
    details: "Détails",
    location: "Emplacement",
    reportHeader: "Signaler un Problème Civique Local",
    reportSub: "Prenez une photo du problème. Notre IA classera automatiquement la catégorie, la gravité et suggérera le département responsable.",
    photoRequired: "Photo du Problème (Obligatoire)",
    uploadText: "Télécharger ou Prendre une Photo",
    uploadSub: "Accepte n'importe quelle photo d'appareil",
    aiAnalyzing: "L'IA analyse votre image...",
    aiAnalyzingSub: "Détection du problème, de la gravité et du département",
    aiComplete: "Classification Automatique par IA Terminée !",
    aiSuggesting: "L'IA analyse la description pour suggérer la catégorie et la gravité...",
    aiSuggestBtn: "Suggérer avec l'IA",
    confidence: "Score de Confiance",
    issueTitle: "Titre du Problème",
    category: "Catégorie",
    severity: "Niveau de Gravité",
    description: "Description Détaillée",
    descriptionPlaceholder: "Fournissez du contexte comme des points de repère à proximité ou des dangers...",
    suggestedDept: "Département Suggéré",
    pinpointLocation: "Localiser Précisément le Problème",
    mapClickTip: "Cliquez n'importe où sur la carte ou faites glisser le marqueur pour indiquer précisément où se trouve le problème.",
    resetGps: "Réinitialiser au GPS",
    latitude: "Latitude",
    longitude: "Longitude",
    gpsLive: "GPS Actif",
    gpsLoading: "Chargement du GPS...",
    gpsUnavailable: "GPS non disponible",
    submitReport: "Soumettre le Signalement",
    submitting: "Envoi du signalement...",
    inspections: "Inspection Virtuelle du Site",
    inspectionTip: "Inspectez l'environnement pour vérifier les détails, rechercher des repères ou valider les blocages civiques signalés directement depuis votre écran.",
    geoLoc: "Emplacement Géographique",
    timeline: "Chronologie de Progression",
    upvotes: "Votes",
    others: "Autres",
    viewProfile: "Voir le Profil",
    pointsEarned: "Points Totaux",
    submissions: "Mes Soumissions",
    personalSettings: "Paramètres Personnels",
    badgesTab: "Badges & Succès",
    updateSuccess: "Profil mis à jour avec succès !",
    saveChanges: "Enregistrer les modifications",
    bioLabel: "Biographie / Déclaration de Contribution",
    phoneLabel: "Numéro de Téléphone",
    notificationsEnabledLabel: "Activer les Alertes E-mail",
    chooseAvatar: "Choisir un Emoji d'Avatar",
    yourRank: "Rang du Classement",
    videoOptional: "Preuve Vidéo (Optionnel)",
    videoUploadSub: "Court extrait vidéo de moins de 750KB pour un contexte dynamique.",
    videoUploading: "Chargement de la vidéo...",
    removeVideo: "Supprimer la vidéo",
    incidentDate: "Date de l'incident",
    incidentDateSub: "Précisez la date à laquelle ce problème a été observé pour la première fois",
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('language');
    if (saved && ['en', 'es', 'fr', 'hi', 'mr'].includes(saved)) {
      return saved as LanguageCode;
    }
    // Default to Marathi if user is from region, otherwise English
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
